//
//  DogsListViperRouter.swift
//  WizelineArchitectuesSMES
//
//  Created Adrian Piedra on 09/03/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

final class DogsListViperRouter: DogsListViperRouterProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = DogsListViperViewController()
        let interactor = DogsListViperInteractor(api: DogAPI())
        let router = DogsListViperRouter()
        let presenter = DogsListViperPresenter(interface: view, interactor: interactor, router: router)
        
        //Bind
        view.presenter = presenter  // View -> Presenter
        interactor.presenter = presenter    // Interactor -> Presenter
        router.viewController = view    // Reference to get NavigationController
        
        return view
    }
    
    func goToDogDetail(dog: Dog) {
        let dogDetailVC = DogDetailViperRouter.createModule(dog: dog)
        viewController?.navigationController?.pushViewController(dogDetailVC, animated: true)
    }
}


