//
//  DogsListViperInteractor.swift
//  WizelineArchitectuesSMES
//
//  Created Adrian Piedra on 09/03/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

final class DogsListViperInteractor: DogsListViperInteractorProtocol {
    //MARK: - API DogsListViperInteractorProtocol
    private(set) var api: DogAPI
    
    //Bind to Presenter
    weak var presenter: DogsListViperPresenterProtocol?
    
    //MARK: - Initializers
    init(api: DogAPI) {
        self.api = api
    }
    
    //MARK: - Methods
    func getDogs() {
        //It execute the API request and notify to the presenter the results
        api.getDogs { [weak self] dogs in
            self?.presenter?.didLoadDogs(status: .finished(data: dogs))
        }
    }
}



