//
//  DogDetailViperProtocols.swift
//  WizelineArchitectuesSMES
//
//  Created Adrian Piedra on 09/03/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Router -
protocol DogDetailViperWireframeProtocol: AnyObject {
    
}
//MARK: Presenter -
protocol DogDetailViperPresenterProtocol: AnyObject {
    var dog: Dog { get set }
}

//MARK: Interactor -
protocol DogDetailViperInteractorProtocol: AnyObject {

  var presenter: DogDetailViperPresenterProtocol?  { get set }
}

//MARK: View -
protocol DogDetailViperViewProtocol: AnyObject {

  var presenter: DogDetailViperPresenterProtocol?  { get set }
}
