//
//  DogDetailViperInteractor.swift
//  WizelineArchitectuesSMES
//
//  Created Adrian Piedra on 09/03/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DogDetailViperInteractor: DogDetailViperInteractorProtocol {

    weak var presenter: DogDetailViperPresenterProtocol?
}
