//
//  DogDetailViperPresenter.swift
//  WizelineArchitectuesSMES
//
//  Created Adrian Piedra on 09/03/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DogDetailViperPresenter: DogDetailViperPresenterProtocol {
    
    //MARK: - DogDetailViperPresenterProtocol Properties
    var dog: Dog
    
    //MARK: - Binding
    weak private var view: DogDetailViperViewProtocol?
    var interactor: DogDetailViperInteractorProtocol?
    private let router: DogDetailViperWireframeProtocol
    
    //MARK: - Initializers
    init(interface: DogDetailViperViewProtocol, interactor: DogDetailViperInteractorProtocol?, router: DogDetailViperWireframeProtocol, dog: Dog) {
        self.view = interface
        self.interactor = interactor
        self.router = router
        
        self.dog = dog
    }

}
