//
//  DogDetailViperRouter.swift
//  WizelineArchitectuesSMES
//
//  Created Adrian Piedra on 09/03/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DogDetailViperRouter: DogDetailViperWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(dog: Dog) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = DogDetailViperViewController()
        let interactor = DogDetailViperInteractor()
        let router = DogDetailViperRouter()
        let presenter = DogDetailViperPresenter(interface: view, interactor: interactor, router: router, dog: dog)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
